data_base:
  database: 'whdata'
  #  database: 'test'
  #####################强哥数据库######################
  #  host: '192.168.0.105'
  #  user: 'root'
  #  password: 'yanye2015'
  #####################################################
  ##################本地数据库#########################
  host: '127.0.0.1'
  user: 'root'
  password: '123456'
  #####################################################
  charset: 'utf8'
  port: 3306

########################定时任务执行参数################################
task:
  when_time: 'day'
  at_day_start_time: '00:00:00'
  sleep_time: 10
########################################################################

# 运营中心,消防管家系统的根域名
system_url: 'http://www.gsafetycloud.com/{}'

api_url:
  ########################################POST##################################################
  #############################################运营中心############################################
  toLogin: 'operation-management/login/toLogin1.mvc'# 登录
  getUserMsg: 'operation-management/user/getUserMsg.mvc' # 运营中心获取用户信息
  mapLocation: 'api/v1.1/operation-management/gisView/{}' # 运营中心获取地图所有数据
  #############################################消防管家############################################
  fh_user_info_url: 'api/v1/fire-society/sys/user/getUserMsg.mvc' # 消防管家获取用户信息
  queryAlarmEmsAccidentCountInfo: 'api/v1/fire-society/group/index/{}' # 地图单位详细信息{'unitId': 530102YZDW201811230002}
  queryAlarmInfo: 'api/v1/fire-society/group/index/{}' # 企业报警信息{'orgCode': WHXFDD_JT_201910110}
  queryTodayAlarmCountTop5: 'api/v1/fire-society/group/index/{}' # 实时报警{'orgCode': WHXFDD_JT_201910110}
  queryTodayAccidentCheckCountTop5: 'api/v1/fire-society/group/index/{}' # 监测故障{'orgCode': WHXFDD_JT_201910110}
  queryTodayHiddenCountTop5: 'api/v1/fire-society/group/index/{}' # 当前隐患{'orgCode': WHXFDD_JT_201910110}
  getTAndAByUnitId: 'api/v1/monitorCenter/monitor/{}' # 单位建筑信息{'unitId': 530102YZDW201811230002}
  getDevicePageByCondition: 'api/v1/monitorCenter/monitor/{}' # 运行监控->监控报表
  # 运行监控->监控报表请求参数
  #{
  #'unitId': 530102YZDW201811230002,
  #'deviceTypePid': configs['monitor_report']['火灾自动报警系统']['deviceTypePid'],
  #'buildId': '', 'deviceTypeId': '', 'runState': '', 'pageNo': '1', 'pageSize': '10'
  #}
  getTAndAByUnitIdAndBuildId: 'api/v1/monitorCenter/monitor/{}' # 单位建筑楼层信息{'unitId': 530102YZDW201811230002, 'buildId': 530102YZDW201811230003_001}
  safetyManager: 'api/v1/fire-society/{}/query' # 信息管理->安全管理{'orgId': org_info['orgCode'], 'attachmentTypeCode': 'AQGL', 'pageNo': 1, 'pageSize': 3, 'safetyAttachName': ''}
  # 信息管理->安全管理参数
  #{'orgId': org_info['orgCode'],
  # 'attachmentTypeCode': 'AQGL'
  # 'pageNo': 1,
  # 'pageSize': 3
  #}
  yearPlan: 'api/v1/fire-society/{}/query' # 消防管家信息管理->年度计划{'orgId': org_info['orgCode'], 'attachmentTypeCode': 'NDJH', 'pageNo': 1, 'pageSize': 3, 'planName': ''}
  # 消防管家信息管理->年度计划
  #{'orgId': org_info['orgCode'],
  # 'attachmentTypeCode': 'NDJH'
  # 'pageNo': 1,
  # 'pageSize': 3
  #}
  maintContract: 'api/v1/fire-society/{}/query' # 消防管家信息管理->维保合同{'orgId': org_info['orgCode'], 'attachmentTypeCode': 'WBHT', 'pageNo': 1, 'pageSize': 3, 'contractName': ''}
  # 消防管家信息管理->维保合同
  #{'orgId': org_info['orgCode'],
  # 'attachmentTypeCode': 'WBHT'
  # 'pageNo': 1,
  # 'pageSize': 3
  #}
  monitReports: 'api/v1/fire-society/{}/query' # 消防管家信息管理->监测报告{'orgId': org_info['orgCode'], 'attachmentTypeCode': 'WBHT', 'pageNo': 1, 'pageSize': 3, 'monitReportName': ''}
  # 消防管家信息管理->监测报告
  #{'orgId': org_info['orgCode'],
  # 'attachmentTypeCode': 'WBHT'
  # 'pageNo': 1,
  # 'pageSize': 3
  #}
  training: 'api/v1/fire-society/{}/query' # 消防管家信息管理->培训演练{'orgId': org_info['orgCode'], 'attachmentTypeCode': 'PXYL', 'pageNo': 1, 'pageSize': 3, 'trainName': ''}
  # 信息管理->安全管理参数
  #{'orgId': org_info['orgCode'],
  # 'attachmentTypeCode': 'PXYL'
  # 'pageNo': 1,
  # 'pageSize': 3
  #}
  planManage: 'api/v1/fire-society/{}/query' # 消防管家信息管理->预案管理{'orgId': org_info['orgCode'], 'attachmentTypeCode': 'YNGL', 'pageNo': 1, 'pageSize': 3, 'planManageName': ''}
  # 消防管家信息管理->预案管理
  #{'orgId': org_info['orgCode'],
  # 'attachmentTypeCode': 'YAGL'
  # 'pageNo': 1,
  # 'pageSize': 3
  #}
  risk: 'api/v1/fire-society/{}/query' # 消防管家信息管理->评估报告{'orgId': org_info['orgCode'], 'attachmentTypeCode': 'FXPGBG', 'pageNo': 1, 'pageSize': 3, 'companyName': ''}
  # 消防管家信息管理->评估报告
  #{'orgId': org_info['orgCode'],
  # 'attachmentTypeCode': 'FXPGBG'
  # 'pageNo': 1,
  # 'pageSize': 3
  #}

  list: 'api/v1/fire-society/controlroom/plan/{}' # 消防管家巡查计划->消控值班室{'pageNo': 1, 'pageSize': 3, 'orgId': '530400YZDW201811230001'}
  list.mvc: 'api/v1/fire-society/inspection/plan/{}' # 消防管家巡查计划->巡查检查,设施巡查
  #消防管家巡查计划->巡查检查参数
  #{'pageNo': 1,
  #'pageSize': 1,
  #'orgId': '530102YZDW201811290002'
  #'searchType': 0
  #}
  #消防管家巡查计划->设施巡查
  #{'pageNo': 1,
  #'pageSize': 1,
  #'orgId': '530102YZDW201811290002',
  #'routingInspectionTypeId': 'C'
  #}

  examineQuery: 'api/v1/fire-society/alarmInfo/{}' # 消防管家安全监管->报警复核
  # 消防管家安全监管->报警复核参数
  #  {'pageNo': 1,
  #  'pageSize': 3,
  #  'proprietorId': '530102YZDW201811290002'}
  accidents: 'api/v1/fire-society/accidentInfo/{}'# 消防管家安全监管->隐患整改
  # 消防管家安全监管->隐患整改参数
  #{'pageNo': 1,
  #'pageSize': 4,
  #'proprietorId': org_info['orgCode']}
  paging: 'api/v1/eRecord/record/enterpriseDevice/{}' # 消防管家设备信息->设备档案{'pageNo': 1, 'pageSize': 4, 'buildId': '', 'floorId': '', deviceName': '', 'unitId': '530102YZDW201811290002'}
  # 消防管家设备信息->设备档案参数
  #{
  #    'unitId': '530102YZDW201811290002',
  #    'pageNo': 1,
  #    'pageSize': 4,
  #}
  #####################################GET##################################################
  getInfoNum: 'api/v1/fire-society/group/index/{}?{}' # 实时报警,检测故障,当前隐患数
  getChildOrg: 'api/v1/fire-society/group/index/{}?{}' # 地图数据,包各单位的orgCode
  #  getInfoNum1: 'api/v1/fire-society/group/index/{}?orgCode={}' # 实时报警,检测故障,当前隐患数
  #  getChildOrg1: 'api/v1/fire-society/group/index/{}?orgCode={}' # 地图数据,包各单位的orgCode
  get_org_info: 'api/v1/eRecord/record/enterprises/1/{}'# 获取消防管家单位信息和图片信息
  fh_org_floor_img: 'image/floorImage/{}' # 消防管家获取单位建筑和楼层图片
  getDeviceListByCondition: 'api/v1/monitorCenter/monitor/{}' # 消防管家探头信息
  # 消防管家探头信息参数
  #{'unitId': '530102YZDW201811290002',
  #'floorId': '530102YZDW201811290002_001_U006',
  # 'buildId': '530102YZDW201811290002_001',
  #}


# 获取消防管家地图 实时报警 监测故障 当前隐患信息接口
post_interface_url:
  ###################以下的请求为{'orgCode':orgCode}##################################
  - 'getUserMsg.mvc' # 运营中心,消防管家获取用户信息
  - 'mapLocation' # 运营中心获取地图所有数据  {orgCode: '530100YYZX201807260001', unitState: '', queryType: '012'}
  - 'queryTodayAlarmCountTop5'  # 消防管家实时报警{'orgCode': WHXFDD_JT_201910110}
  - 'queryTodayAccidentCheckCountTop5'  # 消防管家监测故障{'orgCode': WHXFDD_JT_201910110}
  - 'queryTodayHiddenCountTop5'  # 消防管家当前隐患{'orgCode': WHXFDD_JT_201910110}
  - 'queryAlarmInfo'  # 消防管家企业报警信息{'orgCode': WHXFDD_JT_201910110}
  - 'queryThirtyAlarmCountInfo'  # 消防管家报警趋势{'orgCode': WHXFDD_JT_201910110}
  - 'queryThirtyAccidentCountInfo'  # 消防管家隐患趋势{'orgCode': WHXFDD_JT_201910110}
  ###################以下的请求为{'unitId':orgCode}##################################
  - 'queryAlarmEmsAccidentCountInfo' # 消防管家地图单位详细信息{'unitId': 530102YZDW201811230002}
  - 'getTAndAByUnitId' # 消防管家单位建筑信息{'unitId': 530102YZDW201811230002}
  - 'getTAndAByUnitIdAndBuildId' # 消防管家单位建筑楼层信息{'unitId': 530102YZDW201811230002, 'buildId': 530102YZDW201811230003_001}
  - 'getDevicePageByCondition' # 消防管家运行监测->监测报表{'unitId': 530102YZDW201811230002,'deviceTypePid': configs['monitor_report']['火灾自动报警系统']['deviceTypePid'],'buildId': '','deviceTypeId': '','runState': '', 'pageNo': '1', 'pageSize': '10'}
  - 'safetyManager' # 消防管家信息管理->安全管理 {'orgId': org_info['orgCode'], 'attachmentTypeCode': 'AQGL', 'pageNo': 1, 'pageSize': 3}
  - 'yearPlan' # 消防管家信息管理->年度计划
  - 'maintContract' # 消防管家信息管理->维保合同
  - 'monitReports' # 消防管家信息管理->监测报告
  - 'training' # 消防管家信息管理->培训演练
  - 'planManage'# 消防管家信息管理->预案管理
  - 'risk' # 消防管家信息管理->评估报告
  - 'list' # 消防管家巡查计划->消控值班室{'pageNo': 1, 'pageSize': 3, 'orgId': '530400YZDW201811230001'}
  - 'list.mvc' # 消防管家巡查计划->巡查检查{'pageNo': 1, 'pageSize': 1, 'orgId': '530102YZDW201811290002'}
  - 'examineQuery' # 消防管家安全监管->报警复核{'pageNo': 1, 'pageSize': 3, 'proprietorId': org_info['orgCode'],'alarmTimeStart': '', 'alarmTimeEnd': '', 'build': '', 'alarmNo': ''}
  - 'accidents' # 消防管家安全监管->隐患整改{'pageNo': 1, 'pageSize': 4, 'proprietorId': org_info['orgCode'], 'accidentTimeStart':'', 'accidentTimeEnd': '', 'processState': '', 'isOverdued': '', 'datepicker': '', 'accidentNo': ''}
  - 'paging' # 消防管家设备信息->设备档案{'pageNo': 1, 'pageSize': 4, 'buildId': '', 'floorId': '', deviceName': '', 'unitId': '530102YZDW201811290002'}
  #  - 'getHomeTaskList'
  #  - 'req_user_info_data'# 消防管家运行监测.监测报表{'unitId': 530102YZDW201811230002}
  ##################################################################
  - 'queryLyMonitorInfo' # 消防管家企业,实时报警,实时故障
  - 'getDeviceListByCondition' # 告警探头信息#{'unitId': '530102YZDW201811290002', 'floorId': '530102YZDW201811290002_001_U006', 'buildId': '530102YZDW201811290002_001', 'deviceTypeIds': '', 'runState': ''}

# 获取消防管家地图数据和消防管家实时报警,检测故障,当前隐患数接口
get_interface_url:
  - 'getChildOrg'  # 地图数据,包各单位的orgCode
  - 'getInfoNum'  # 实时报警,检测故障,当前隐患数

# 消防管家运行监测-监测报表
monitor_report:
  火灾自动报警系统:
    deviceTypePid: '02000000'
    deviceTypeId: ''
  用户报警信息传输装置:
    deviceTypePid: '19000000'
    deviceTypeId: '19010000'
  电器火灾监测:
    deviceTypePid: '19000000'
    deviceTypeId: '19050000'
  消防洪水监测:
    deviceTypePid: '19000000'
    deviceTypeId:
      - '19020000'
      - '19030000'
      - '19080000'
      - '19150000'
      - '19180000'
  独立式监测设备:
    deviceTypePid: '19000000'
    deviceTypeId:
      - '19210000'
      - '19230000'

# 登录运营中心账号密码
login_data:
  loginName: 'km01'
  password: 'a123456'
  systemCode: ''
# 登录运营中心加密的盐
salt: 'true'

map_serch_data:
  orgCode: '{}'
  unitState: ''
  queryType: '012'


whxfdd_org_code:
  orgCode: 'WHXFDD_JT_201910110'

# 消防管家加载用户信息请求data
req_user_info_data:
  loginName: 'whxfdd'


